// Athena - Changelog Renderer
// Copyright 2026, Forgeborn

import type { ParsedCommit, VersionSection } from "../types.js";

/**
 * Format a commit line for CHANGELOG.md.
 */
function formatCommitLine(commit: ParsedCommit, githubUrl?: string): string {
  let line = `- ${commit.subject}`;

  // Add PR link
  if (commit.prNumber && githubUrl) {
    line += ` ([#${commit.prNumber}](${githubUrl}/pull/${commit.prNumber}))`;
  }

  // Add issue links
  if (commit.issueNumbers.length > 0 && githubUrl) {
    const issueLinks = commit.issueNumbers.map(
      (n) => `[#${n}](${githubUrl}/issues/${n})`
    );
    line += ` (${issueLinks.join(", ")})`;
  }

  return line;
}

/**
 * Format a commit line with full detail for HISTORY.md.
 */
function formatDetailedCommitLine(commit: ParsedCommit, githubUrl?: string): string {
  let line = `- `;

  // Commit hash link
  if (githubUrl) {
    line += `[\`${commit.shortHash}\`](${githubUrl}/commit/${commit.hash}) `;
  } else {
    line += `\`${commit.shortHash}\` `;
  }

  // Scope prefix
  if (commit.scope) {
    line += `**${commit.scope}:** `;
  }

  line += commit.subject;

  // PR link
  if (commit.prNumber && githubUrl) {
    line += ` ([#${commit.prNumber}](${githubUrl}/pull/${commit.prNumber}))`;
  }

  // Issue links
  if (commit.issueNumbers.length > 0 && githubUrl) {
    const issueLinks = commit.issueNumbers.map(
      (n) => `[#${n}](${githubUrl}/issues/${n})`
    );
    line += ` (${issueLinks.join(", ")})`;
  }

  // Author
  line += ` — *${commit.author}*`;

  return line;
}

/**
 * Render a section of commits under a category heading.
 */
function renderCategory(
  heading: string,
  emoji: string,
  commits: ParsedCommit[],
  githubUrl?: string,
  detailed = false
): string {
  if (commits.length === 0) return "";

  const lines = [`### ${emoji} ${heading}\n`];
  const formatter = detailed ? formatDetailedCommitLine : formatCommitLine;

  for (const commit of commits) {
    lines.push(formatter(commit, githubUrl));
  }

  lines.push("");
  return lines.join("\n");
}

/**
 * Render a single version section.
 */
function renderVersion(
  section: VersionSection,
  githubUrl?: string,
  detailed = false
): string {
  const lines: string[] = [];

  // Version header with date
  if (section.tag && githubUrl) {
    lines.push(
      `## [${section.version}](${githubUrl}/releases/tag/${section.tag}) (${section.date})\n`
    );
  } else {
    lines.push(`## ${section.version} (${section.date})\n`);
  }

  // Breaking changes first (always highlighted)
  if (section.breaking.length > 0) {
    lines.push("### :warning: Breaking Changes\n");
    for (const commit of section.breaking) {
      const formatter = detailed ? formatDetailedCommitLine : formatCommitLine;
      lines.push(formatter(commit, githubUrl));
    }
    lines.push("");
  }

  // Category sections (skip commits already shown as breaking)
  const breakingHashes = new Set(section.breaking.map((c) => c.hash));
  const filterBreaking = (commits: ParsedCommit[]) =>
    commits.filter((c) => !breakingHashes.has(c.hash));

  lines.push(renderCategory("Features", ":sparkles:", filterBreaking(section.features), githubUrl, detailed));
  lines.push(renderCategory("Bug Fixes", ":bug:", filterBreaking(section.fixes), githubUrl, detailed));
  lines.push(renderCategory("Performance", ":zap:", filterBreaking(section.perfs), githubUrl, detailed));
  lines.push(renderCategory("Refactoring", ":recycle:", filterBreaking(section.refactors), githubUrl, detailed));
  lines.push(renderCategory("Documentation", ":memo:", filterBreaking(section.docs), githubUrl, detailed));
  lines.push(renderCategory("Tests", ":white_check_mark:", filterBreaking(section.tests), githubUrl, detailed));
  lines.push(renderCategory("Styles", ":art:", filterBreaking(section.styles), githubUrl, detailed));
  lines.push(renderCategory("CI", ":construction_worker:", filterBreaking(section.ci), githubUrl, detailed));
  lines.push(renderCategory("Chores", ":wrench:", filterBreaking(section.chores), githubUrl, detailed));

  return lines.filter((l) => l !== "").join("\n");
}

/**
 * Render the full CHANGELOG.md content.
 */
export function renderChangelog(
  versions: VersionSection[],
  githubUrl?: string
): string {
  const lines: string[] = [
    "# Changelog\n",
    "All notable changes to this project will be documented in this file.\n",
    "This changelog is auto-generated by [Athena](https://github.com/SBKNana/Athena).\n",
  ];

  for (const version of versions) {
    lines.push(renderVersion(version, githubUrl, false));
  }

  return lines.join("\n") + "\n";
}

/**
 * Render the full HISTORY.md content (detailed version with commit hashes and authors).
 */
export function renderHistory(
  versions: VersionSection[],
  githubUrl?: string
): string {
  const lines: string[] = [
    "# Version History\n",
    "Detailed commit history for this project. For a concise summary, see [CHANGELOG.md](CHANGELOG.md).\n",
    "This history is auto-generated by [Athena](https://github.com/SBKNana/Athena).\n",
  ];

  for (const version of versions) {
    lines.push(renderVersion(version, githubUrl, true));
  }

  return lines.join("\n") + "\n";
}
