// Athena - Diagram Generator Orchestrator
// Copyright 2026, TheForge, LLC

import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import type { ProjectManifest } from "../types.js";
import type { DiagramType, DiagramResult, DiagramGeneratorConfig } from "../types.js";
import {
  generatePackageDependencyGraph,
  generateImportGraph,
} from "./dependency-graph.js";
import { generateDBSchemaDiagram } from "./db-schema.js";
import { generateAPIFlowDiagram } from "./api-flow.js";
import { generateComponentTreeDiagram } from "./component-tree.js";
import { generateFileStructureDiagram } from "./file-structure.js";
import { generateDataFlowDiagram } from "./data-flow.js";
import { renderMermaidBatch, isMermaidCliAvailable } from "./renderer.js";
import type { OutputFormat, RenderResult } from "./renderer.js";

const ALL_DIAGRAM_TYPES: DiagramType[] = [
  "dependency",
  "imports",
  "db-schema",
  "api-flow",
  "component-tree",
  "file-structure",
  "data-flow",
];

export class DiagramGenerator {
  private config: DiagramGeneratorConfig;

  constructor(config: DiagramGeneratorConfig) {
    this.config = config;
  }

  async generate(manifest: ProjectManifest): Promise<DiagramResult> {
    const types = this.config.types || ALL_DIAGRAM_TYPES;
    const diagrams: Array<{ name: string; type: DiagramType; code: string }> = [];
    const errors: Array<{ type: DiagramType; error: string }> = [];

    for (const type of types) {
      try {
        const code = await this.generateDiagram(type, manifest);
        if (code && isMeaningfulDiagram(code)) {
          diagrams.push({ name: type, type, code });
        }
      } catch (err) {
        errors.push({
          type,
          error: err instanceof Error ? err.message : String(err),
        });
      }
    }

    // Write Mermaid source files
    const outputDir = this.config.outputDir;
    await mkdir(outputDir, { recursive: true });

    for (const diagram of diagrams) {
      const mmdPath = join(outputDir, `${diagram.name}.mmd`);
      await writeFile(mmdPath, diagram.code, "utf-8");
    }

    // Render to PNG/SVG if requested
    let renderResults: RenderResult[] = [];
    if (this.config.render) {
      const renderFormat = this.config.format || "both";
      const hasCli = await isMermaidCliAvailable();

      if (hasCli) {
        renderResults = await renderMermaidBatch(
          diagrams.map((d) => ({ name: d.name, code: d.code })),
          outputDir,
          renderFormat
        );
      } else {
        console.log(
          "  Note: @mermaid-js/mermaid-cli not found. Mermaid source files (.mmd) saved."
        );
        console.log(
          "  Install for image rendering: npm install -g @mermaid-js/mermaid-cli"
        );
      }
    }

    // Generate markdown doc with embedded diagrams
    if (this.config.markdown) {
      const mdPath = join(outputDir, "DIAGRAMS.md");
      const mdContent = buildMarkdownDoc(diagrams, manifest, renderResults);
      await writeFile(mdPath, mdContent, "utf-8");
    }

    return {
      diagrams: diagrams.map((d) => ({
        type: d.type,
        name: d.name,
        mermaidCode: d.code,
        mmdPath: join(outputDir, `${d.name}.mmd`),
        renderResults: renderResults.filter((r) => r.name === d.name),
      })),
      errors,
      outputDir,
      markdownPath: this.config.markdown
        ? join(outputDir, "DIAGRAMS.md")
        : undefined,
    };
  }

  private async generateDiagram(
    type: DiagramType,
    manifest: ProjectManifest
  ): Promise<string> {
    switch (type) {
      case "dependency":
        return generatePackageDependencyGraph(manifest);
      case "imports":
        return await generateImportGraph(this.config.projectDir, manifest);
      case "db-schema":
        return await generateDBSchemaDiagram(this.config.projectDir);
      case "api-flow":
        return await generateAPIFlowDiagram(this.config.projectDir, manifest);
      case "component-tree":
        return await generateComponentTreeDiagram(
          this.config.projectDir,
          manifest
        );
      case "file-structure":
        return await generateFileStructureDiagram(this.config.projectDir);
      case "data-flow":
        return await generateDataFlowDiagram(this.config.projectDir, manifest);
      default:
        return "";
    }
  }
}

function buildMarkdownDoc(
  diagrams: Array<{ name: string; type: DiagramType; code: string }>,
  manifest: ProjectManifest,
  renderResults: RenderResult[]
): string {
  const lines: string[] = [];

  lines.push(`# ${manifest.name} - Architecture Diagrams`);
  lines.push("");
  lines.push(`Generated by Athena v${manifest.athenaVersion} on ${new Date().toISOString()}`);
  lines.push("");
  lines.push(`**Framework:** ${manifest.framework} | **Language:** ${manifest.language}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Table of contents
  lines.push("## Table of Contents");
  lines.push("");
  for (const diagram of diagrams) {
    const title = getDiagramTitle(diagram.type);
    const anchor = title.toLowerCase().replace(/[^a-z0-9]+/g, "-");
    lines.push(`- [${title}](#${anchor})`);
  }
  lines.push("");

  // Each diagram section
  for (const diagram of diagrams) {
    const title = getDiagramTitle(diagram.type);
    lines.push(`## ${title}`);
    lines.push("");
    lines.push(getDiagramDescription(diagram.type));
    lines.push("");

    // Check if we have a rendered image
    const pngResult = renderResults.find(
      (r) => r.name === diagram.name && r.format === "png" && r.success
    );
    const svgResult = renderResults.find(
      (r) => r.name === diagram.name && r.format === "svg" && r.success
    );

    if (svgResult) {
      lines.push(`![${title}](./${diagram.name}.svg)`);
      lines.push("");
    } else if (pngResult) {
      lines.push(`![${title}](./${diagram.name}.png)`);
      lines.push("");
    }

    // Always include the Mermaid source
    lines.push("<details>");
    lines.push(`<summary>Mermaid source</summary>`);
    lines.push("");
    lines.push("```mermaid");
    lines.push(diagram.code);
    lines.push("```");
    lines.push("");
    lines.push("</details>");
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  return lines.join("\n");
}

function getDiagramTitle(type: DiagramType): string {
  const titles: Record<DiagramType, string> = {
    dependency: "Package Dependencies",
    imports: "Import Graph",
    "db-schema": "Database Schema",
    "api-flow": "API Request Flow",
    "component-tree": "Component Tree",
    "file-structure": "File Structure",
    "data-flow": "Data Flow",
  };
  return titles[type] || type;
}

/**
 * Check if a diagram has enough content to be useful.
 * Filters out diagrams that only have boilerplate (e.g., just participant lines).
 */
function isMeaningfulDiagram(code: string): boolean {
  const lines = code.split("\n").map((l) => l.trim()).filter((l) => l);
  // Need at least 3 lines (header + 2 content lines)
  if (lines.length < 3) return false;

  // For sequence diagrams, need at least one arrow (->>, -->>)
  if (lines[0] === "sequenceDiagram") {
    return lines.some((l) => l.includes("->>") || l.includes("-->>"));
  }

  return true;
}

function getDiagramDescription(type: DiagramType): string {
  const descriptions: Record<DiagramType, string> = {
    dependency:
      "Runtime and development dependencies from package.json. Solid arrows = runtime deps, dashed = dev deps.",
    imports:
      "Local import relationships between source files/modules.",
    "db-schema":
      "Entity-relationship diagram of the database schema (from Prisma, SQL, or ORM entities).",
    "api-flow":
      "Sequence diagram showing the request lifecycle through middleware and handlers.",
    "component-tree":
      "React/Next.js component hierarchy showing parent-child relationships.",
    "file-structure":
      "Directory tree of important project files and folders.",
    "data-flow":
      "End-to-end data flow tracing requests from UI through API to the database and back.",
  };
  return descriptions[type] || "";
}
